#!/bin/bash

set -e 

echo
echo "### HOOK - build environment:"
echo "   SOURCE_BRANCH  : $SOURCE_BRANCH"
echo "   SOURCE_COMMIT  : $SOURCE_COMMIT"
echo "   COMMIT_MSG     : $COMMIT_MSG"
echo "   DOCKER_REPO    : $DOCKER_REPO"
echo "   DOCKERFILE_PATH: $DOCKERFILE_PATH"
echo "   DOCKER_TAG     : $DOCKER_TAG"
echo "   DOCKER_TAG     : $IMAGE_NAME"

echo

docker build -f ./Dockerfile.x86 -t ${DOCKER_REPO}:${DOCKER_TAG} .
docker build -f ./Dockerfile.x86 -t ${DOCKER_REPO}:latest .

docker build -f ./Dockerfile.ARM -t ${DOCKER_REPO}:arm-${DOCKER_TAG} .
docker build -f ./Dockerfile.ARM -t ${DOCKER_REPO}:arm-latest .